version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "06:00"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "[actions] "
      include: scope
    labels:
      - "bump-deps"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[nuget] "
      include: scope
    labels:
      - "bump-deps"

  - package-ecosystem: 'npm'
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[npm] "
      include: scope
    labels:
      - "bump-deps"